Repository ember-cli/ember-try, pull requests merged in 2024-12, with the labels that each got.

#969 Update development dependencies
  .github/workflows/ci.yml
  .github/workflows/release.yml
  lib/commands/try-one.js
  lib/dependency-manager-adapters/npm.js
  lib/dependency-manager-adapters/pnpm.js
  lib/dependency-manager-adapters/workspace.js
  lib/tasks/reset.js
  lib/tasks/try-each.js
  lib/utils/config.js
  lib/utils/dependency-manager-adapter-factory.js
  lib/utils/scenario-manager.js
  package.json
  test/commands/try-one-test.js
  test/dependency-manager-adapters/npm-adapter-test.js
  test/dependency-manager-adapters/pnpm-adapter-test.js
  test/dependency-manager-adapters/workspace-adapter-test.js
  test/fixtures/dummy-ember-try-config-different-env-vars.js
  test/helpers/assert-file-contains-json.js
  test/helpers/generate-mock-run.js
  test/tasks/try-each-test.js
  test/utils/config-test.js
  test/utils/dependency-manager-adapter-factory-test.js
  yarn.lock
Labels: internal

#994 pnpm: Ignore scripts by default
  lib/dependency-manager-adapters/pnpm.js
  test/dependency-manager-adapters/pnpm-adapter-test.js
Labels: breaking

#1002 Clean up everything related to Bower
  .eslintignore
  .gitignore
  .npmignore
  lib/utils/dependency-manager-adapter-factory.js
  smoke-test-app/.eslintignore
  smoke-test-app/.gitignore
  smoke-test-app/.npmignore
  smoke-test-app/.prettierignore
  test/utils/dependency-manager-adapter-factory-test.js
Labels: internal

#1001 Update ESLint config to properly support native classes
  .eslintrc.js
  package.json
  yarn.lock
Labels: internal

#1020 Remove use of `core-object` for adapters
  lib/dependency-manager-adapters/npm.js
  lib/dependency-manager-adapters/pnpm.js
  lib/dependency-manager-adapters/workspace.js
  package.json
  test/helpers/stub-dependency-manager-adapter.js
  test/utils/scenario-manager-test.js
Labels: internal

#1023 Use `ember version` command to make test output more readable
  test/tasks/try-each-test.js
Labels: internal

#807 Use scenario names available in default `addon` blueprint
  README.md
Labels: documentation

#1024 Update all dependencies with non-breaking changes
  package.json
  yarn.lock
Labels: dependencies

#1022 Use only one ESLint config file
  .eslintrc.js
  test/.eslintrc.js
Labels: internal

#1025 Support a `packageManager` option (instead of `usePnpm` and `useYarn`)
  README.md
  lib/dependency-manager-adapters/npm.js
  lib/dependency-manager-adapters/workspace.js
  lib/utils/config.js
  lib/utils/dependency-manager-adapter-factory.js
  test/dependency-manager-adapters/workspace-adapter-test.js
  test/fixtures/dummy-ember-try-config-with-yarn-scenarios.js
  test/tasks/try-each-test.js
  test/utils/config-test.js
  test/utils/dependency-manager-adapter-factory-test.js
Labels: enhancement

#1027 Update lint setup
  .codeclimate.yml
  .eslintrc.js
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .prettierignore
  README.md
  RELEASE.md
  package.json
  smoke-test-app/README.md
  smoke-test-app/tests/dummy/app/index.html
  smoke-test-app/tests/dummy/config/ember-cli-update.json
  smoke-test-app/tests/dummy/config/ember-try.js
  smoke-test-app/tests/index.html
  test/fixtures/package-with-workspaces.json
  test/fixtures/package.json
  yarn.lock
Labels: internal

#1028 Remove some unused files
  .editorconfig
  ember-cli-build.js
  testem.js
Labels: internal

#1029 Remove use of `mockery`
  lib/utils/run.js
  package.json
  test/helpers/generate-mock-run.js
  test/tasks/try-each-test.js
  test/utils/run-command-test.js
  yarn.lock
Labels: internal

#1030 Remove use of ember-cli `ui` instance
  lib/commands/config.js
  lib/commands/try-each.js
  lib/commands/try-ember.js
  lib/commands/try-one.js
  lib/dependency-manager-adapters/base.js
  lib/dependency-manager-adapters/pnpm.js
  lib/dependency-manager-adapters/workspace.js
  lib/tasks/try-each.js
  lib/utils/config.js
  lib/utils/console.js
  lib/utils/result-summary.js
  lib/utils/scenario-manager.js
  test/tasks/try-each-test.js
Labels: internal

#1034 Migrate test suite to ES modules
  .eslintrc.js
  package.json
  test/commands/try-each-test.js
  test/commands/try-ember-test.js
  test/commands/try-one-test.js
  test/dependency-manager-adapters/npm-adapter-test.js
  test/dependency-manager-adapters/pnpm-adapter-test.js
  test/dependency-manager-adapters/workspace-adapter-test.js
  test/dependency-manager-adapters/yarn-adapter-test.js
  test/helpers/assert-file-contains-json.js
  test/helpers/generate-mock-run.js
  test/helpers/stub-dependency-manager-adapter.js
  test/helpers/write-json-file.js
  test/package.json
  test/tasks/reset-test.js
  test/tasks/try-each-test.js
  test/utils/config-test.js
  test/utils/dependency-manager-adapter-factory-test.js
  test/utils/find-ember-path-test.js
  test/utils/run-command-test.js
  test/utils/run-test.js
  test/utils/scenario-manager-test.js
  yarn.lock
Labels: internal

#1035 Remove custom `findByName` util
  lib/commands/try-one.js
  lib/utils/config.js
  lib/utils/find-by-name.js
Labels: internal

#1038 Swap to pnpm
  .github/workflows/ci.yml
  .prettierignore
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: internal
